### ISSUE TITLE
[Feature Request] Options for mini and map

### ISSUE THREAD

**Issue by Stanzilla** [kemayo/wow-handynotes-legiontreasures#4]
some people might only want the one or the other, so options to enable/disable each part of the addon would be nice:

*  minimap / map icons: Currently most people set alpha to zero of the part they don't want to see, a real option would be neat.
* Treasures / Rares: Only a problem on Argus and similar content where treasures are not a guaranteed spawn but random. 

and probably a combination of those two. Also the treasures of the http://www.wowhead.com/achievement=12074/shoot-first-loot-later achievement should probably be treated differently than the normal ones.

**Comment by kemayo** [comment]
f5088fa addresses the Argus issue, I feel.

**Comment by kemayo** [comment]
I think that 2f57fb2 addresses everything remaining. There's now config options for world map / minimap display, and a toggle for hiding treasure to go along with the already extant one for hiding rares.
