### ISSUE TITLE
Errors (this time) in Thorgast....

### ISSUE THREAD

**Issue by manuelando** [kemayo/wow-handynotes-legiontreasures#8]
Dude..... this addon is full of errors, i got 9 different errors repeated countless times, just playing in Thorgast. This sh*it is unusable.... lol. Untill now i was lazy to post the countless errors of Hantynotes addons, but im sick of this shit now. The following are only in thorgast, i'll post more as i can from now on.

HandyNotes_LegionTreasures blocked from using <unnamed>:ClearAllPoints()
Count: 69

Call Stack:
[string "=[C]"]: in function `ClearAllPoints'
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:1059: in function <...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:1055>
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:1477: in function `ObjectiveTracker_ReorderModules'
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:1398: in function `ObjectiveTracker_Update'
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:846: in function <...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:844>

HandyNotes_LegionTreasures blocked from using <unnamed>:SetPoint()
Count: 69

Call Stack:
[string "=[C]"]: in function `SetPoint'
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:1083: in function <...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:1055>
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:1477: in function `ObjectiveTracker_ReorderModules'
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:1398: in function `ObjectiveTracker_Update'
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:846: in function <...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:844>

HandyNotes_LegionTreasures blocked from using <unnamed>:Show()
Count: 34

Call Stack:
[string "=[C]"]: in function `Show'
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:1132: in function `ObjectiveTracker_AddHeader'
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:1148: in function `ObjectiveTracker_AddBlock'
[string "@Blizzard_ObjectiveTracker\Blizzard_ScenarioObjectiveTracker.lua"]:867: in function `StaticReanchor'
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:1393: in function `ObjectiveTracker_Update'
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:846: in function <...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:844>

HandyNotes_LegionTreasures blocked from using ScenarioBlocksFrame:ClearAllPoints()
Count: 34

Call Stack:
[string "=[C]"]: in function `ClearAllPoints'
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:1059: in function <...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:1055>
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:1108: in function <...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:1091>
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:1149: in function `ObjectiveTracker_AddBlock'
[string "@Blizzard_ObjectiveTracker\Blizzard_ScenarioObjectiveTracker.lua"]:867: in function `StaticReanchor'
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:1393: in function `ObjectiveTracker_Update'
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:846: in function <...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:844>

HandyNotes_LegionTreasures blocked from using ScenarioBlocksFrame:SetPoint()
Count: 68

Call Stack:
[string "=[C]"]: in function `SetPoint'
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:1072: in function <...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:1055>
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:1108: in function <...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:1091>
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:1149: in function `ObjectiveTracker_AddBlock'
[string "@Blizzard_ObjectiveTracker\Blizzard_ScenarioObjectiveTracker.lua"]:867: in function `StaticReanchor'
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:1393: in function `ObjectiveTracker_Update'
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:846: in function <...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:844>

HandyNotes_LegionTreasures blocked from using <unnamed>:Hide()
Count: 30

Call Stack:
[string "=[C]"]: in function `Hide'
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:143: in function `BeginLayout'
[string "@Blizzard_ObjectiveTracker\Blizzard_ScenarioObjectiveTracker.lua"]:925: in function `Update'
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:1380: in function `ObjectiveTracker_Update'
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:1016: in function <...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:1009>

HandyNotes_LegionTreasures blocked from using ScenarioStageBlock:ClearAllPoints()
Count: 30

Call Stack:
[string "=[C]"]: in function `ClearAllPoints'
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:1059: in function <...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:1055>
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:1108: in function <...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:1091>
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:1149: in function `ObjectiveTracker_AddBlock'
[string "@Blizzard_ObjectiveTracker\Blizzard_ScenarioObjectiveTracker.lua"]:976: in function `Update'
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:1380: in function `ObjectiveTracker_Update'
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:1016: in function <...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:1009>

HandyNotes_LegionTreasures blocked from using ScenarioStageBlock:SetPoint()
Count: 30

Call Stack:
[string "=[C]"]: in function `SetPoint'
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:1085: in function <...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:1055>
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:1108: in function <...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:1091>
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:1149: in function `ObjectiveTracker_AddBlock'
[string "@Blizzard_ObjectiveTracker\Blizzard_ScenarioObjectiveTracker.lua"]:976: in function `Update'
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:1380: in function `ObjectiveTracker_Update'
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:1016: in function <...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:1009>

HandyNotes_LegionTreasures blocked from using ScenarioStageBlock:Show()
Count: 30

Call Stack:
[string "=[C]"]: in function `Show'
[string "@Blizzard_ObjectiveTracker\Blizzard_ScenarioObjectiveTracker.lua"]:977: in function `Update'
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:1380: in function `ObjectiveTracker_Update'
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:1016: in function <...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:1009>

HandyNotes_LegionTreasures blocked from using ScenarioBlocksFrame:SetHeight()
Count: 31

Call Stack:
[string "=[C]"]: in function `SetHeight'
[string "@Blizzard_ObjectiveTracker\Blizzard_ScenarioObjectiveTracker.lua"]:1059: in function `Update'
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:1380: in function `ObjectiveTracker_Update'
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:1016: in function <...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:1009>

HandyNotes_LegionTreasures blocked from using ScenarioBlocksFrame:Show()
Count: 30

Call Stack:
[string "=[C]"]: in function `Show'
[string "@Blizzard_ObjectiveTracker\Blizzard_ScenarioObjectiveTracker.lua"]:1061: in function `Update'
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:1380: in function `ObjectiveTracker_Update'
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:1016: in function <...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:1009>

**Comment by kemayo** [comment]
This doesn't happen to me, which makes it hard to address.

It's a [taint issue](https://wowpedia.fandom.com/wiki/Secure_Execution_and_Tainting), which means it can be a complicated set of addons interacting that causes it, with the blame falling on whichever one happened to be loaded first (particularly if it's libraries causing it). Can you let me know if this still happens if Handynotes is the only addon you have enabled?

**Comment by kemayo** [comment]
I've made some substitutions to hopefully avoid things like this. Reopen if you see it again.
