### ISSUE TITLE
Upgrading an Item at Oribos

### ISSUE THREAD

**Issue by manuelando** [kemayo/wow-handynotes-legiontreasures#9]
HandyNotes_LegionTreasures forbidden from using UpgradeItem() (Only usable by Blizzard)
Count: 2

Call Stack:
[string "=[C]"]: in function `UpgradeItem'
[string "@Blizzard_ItemUpgradeUI\Blizzard_ItemUpgradeUI.lua"]:104: in function `OnConfirm'
[string "@FrameXML\StaticPopup.lua"]:342: in function `OnAccept'
[string "@FrameXML\StaticPopup.lua"]:5192: in function `StaticPopup_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

**Comment by kemayo** [comment]
I've made a few substitutions to hopefully avoid taint like this. Reopen if you see this again.
